### ISSUE TITLE
Crazy issue with TAP

### ISSUE THREAD

**Issue by tonypujals** [substack/browserify-adventure#21]
Posting this issue on behalf of a user I'm trying to help. I can't duplicate on my own machine, and not sure anyone else can.

We have tried clean installs of the latest versions of Node for the following release lines:  v0.10.x, v0.12, v4.0.  We have completely blown away node, and global and home directories for node_modules, .npm, etc., and reinstalled browserify-adventure multiple times after deletion.

No matter, what she is getting this error on her system when we run verify for the very first lesson.

Contents of main.js

```
console.log('BEEP BOOP');
```

And result...

```
$ browserify index.js | browserify-adventure verify

TAP version 13
# (anonymous)
not ok 1 2 files
  ---
    operator: equal
    expected: 2
    actual:   226
    at: ConcatStream.<anonymous> (/usr/local/lib/node_modules/browserify-adventure/node_modules/concat-stream/index.js:36:43)
  ...
not ok 2 entry file has a single "uniq" dependency
  ---
    operator: deepEqual
    expected: [ 'uniq' ]
    actual:   [ 'prompt', 'uniq' ]
    at: ConcatStream.<anonymous> (/usr/local/lib/node_modules/browserify-adventure/node_modules/concat-stream/index.js:36:43)
  ...

undefined:876
  var files = fs.readdirSync(dir);
                 ^
TypeError: undefined is not a function
    at Function.pkginfo.find (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:876:18)
    at Function.pkginfo.read (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:900:17)
    at module.exports (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:850:21)
    at Object.eval (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:913:1)
    at Object.fs (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:918:4)
    at s (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:3:254)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:3:305)
    at Object../winston/common (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:7388:1)
    at s (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:3:254)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/browserify-adventure/problems/using_npm_packages/index.js:60:49), <anonymous>:3:305)
```

Any suggestions from anyone?

**Comment by fcouillard** [comment]
You are compiling index.js instead of main.js?
